apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fglwkojuu-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:85ca4fb3b0fe11c81539b93cde0601300706a122@sha256:8fe529ac2be4600e3fbc8186ce3d3f5977ce533bcdd6f6269cc71b81ee704bd5
          name: container-image
